### ISSUE TITLE
TFlearn error with latest tensorflow commit

### ISSUE THREAD

**Issue by callumherries** [tflearn/tflearn#480]
Today I tried building tensorflow from the latest commit on Windows and it didn't seem to work with TFlearn.

For example, when I ran the logical.py example:

``
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    m = tflearn.DNN(g)
  File "C:\Users\Callum\Anaconda3\envs\py35\lib\site-packages\tflearn\models\dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "C:\Users\Callum\Anaconda3\envs\py35\lib\site-packages\tflearn\helpers\trainer.py", line 134, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "C:\Users\Callum\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "C:\Users\Callum\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\training\saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
``

The tensorflow examples (with TFlearn) all run fine.

**Comment by marcotrombetti** [comment]
Same problem here.

To reproduce:
Install TensorFlow 0.11.on a P2 AWS Machine using:
http://expressionflow.com/2016/10/09/installing-tensorflow-on-an-aws-ec2-p2-gpu-instance/

Installed TF from Git using:
```
pip install git+https://github.com/tflearn/tflearn.git
```

Running most of the NLP Examples will give:
```
ubuntu@ip-172-30-4-101:~/devel/T-Rank-DL-Classifier$ python linear_regression.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5.1.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:1e.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0)
Traceback (most recent call last):
  File "linear_regression.py", line 16, in <module>
    m = tflearn.DNN(regression)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 63, in __init__
    best_val_accuracy=best_val_accuracy)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/trainer.py", line 134, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1028, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1049, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

**Comment by AAvi** [comment]
Same here. The problem seems to be in line 1021, in execution of tflearn.DNN(convnet)

**Comment by DavidMChan** [comment]
I found that the error was resolved for me by adding a check to tflearn/helpers/trainer.py at line 134:

```{python}
if not not to_restore:
                self.restorer = tf.train.Saver(
                    var_list=to_restore,
                    max_to_keep=max_checkpoints,
                    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
```

However this leads to an additional error on using uninitialized variables in training. Will update if I can resolve this issue as well.

**Comment by guduxingzou** [comment]
Same here. I used windows  py3.5 tf0.12

**Comment by werner-rammer** [comment]
I experienced the same issue. It seems to be related with the `tf.GraphKeys.VARIABLES`. The trainer looks for `VARIABLES`, but all the variables seem to end up in the `TRAINABLE_VARIABLES` collection.
A "fix" that worked for me is to manually add the trainable variables to the `VARIABLES`.
```python
# after the definition of the model:
...
network = regression(network, optimizer='adam', learning_rate=0.01,
                     loss='categorical_crossentropy', name='target')
### add this "fix":
col = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
for x in col:
    tf.add_to_collection(tf.GraphKeys.VARIABLES, x )    
## then continue:
model = tflearn.DNN(network, tensorboard_verbose=0, checkpoint_path='test')
...
```
There are, however, warnings when you a value for `snapshot_step` in the `model.fit()` function (setting to `None` helps, though).

**Comment by callumherries** [comment]
@werner-rammer's fix worked for me.

**Comment by djl11** [comment]
Same Issues for me on all tflearn examples, ubuntu16.04 py3.5 tf0.11

**Comment by avloss** [comment]
same on Mac.. Looks like I've picked wrong time to learn `tflearn`. You guys should FIX a TF version in the `requirements.txt` - because you have link on "latest" - assuming it'll always work is a little ambitions - add tests, and as they pass - increase supported version in the `requiremnets`

**Comment by ellistev** [comment]
I'm attempting to update a few of the files in tflearn to work with tensorflow 0.12, will see how it goes...

**Comment by zzxun** [comment]
Same here. So I make tensorflow back to 0.11 and fix this.

**Comment by aymericdamien** [comment]
We are working to make TFLearn compatible with the new TensorFlow 0.12, sorry for the inconvenience! I suggest to keep using 0.11 for now.

**Comment by HelloGithubTest** [comment]
run into same problem.  I trace the problem a little bit.   here is a diff path on trainer.py which can solve the "ValueError: No variables to save" issue:

--- /usr/local/lib/python2.7/site-packages/tflearn/helpers/trainer.py	2016-12-01 23:05:45.000000000 -0800
+++ /tmp/trainer.py	2016-12-01 22:57:31.000000000 -0800
@@ -125,7 +125,7 @@
                 max_to_keep=max_checkpoints,
                 keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
             # Saver for restoring a model (With exclude variable list)
-            all_vars = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
+            all_vars = tf.get_collection(tf.GraphKeys.VARIABLES)
             excl_vars = tf.get_collection(tf.GraphKeys.EXCL_RESTORE_VARS)
             to_restore = [item for item in all_vars
                           if check_restore_tensor(item, excl_vars)]
@@ -146,7 +146,7 @@
             self.checkpoint_path = checkpoint_path

             if not self.restored:
-                init = tf.global_variables_initializer()
+                init = tf.initialize_all_variables()
                 self.session.run(init)

     def fit(self, feed_dicts, n_epoch=10, val_feed_dicts=None, show_metric=False,

**Comment by HelloGithubTest** [comment]
run into same problem. I trace the problem a little bit. here is a diff path on trainer.py which can solve the "ValueError: No variables to save" issue
[trainer.py.path.txt](https://github.com/tflearn/tflearn/files/626535/trainer.py.path.txt)

**Comment by HelloGithubTest** [comment]
by the way there are more problems with TensorFlow 0.12.  following are some error messages when i use lstm or bidirectional_rnn: hope you guys can solve it asap

WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing layer_tensor/BiRNN.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'list' object has no attribute 'name'

..........

WARNING:tensorflow:Error encountered when serializing layer_tensor/BiRNN.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'list' object has no attribute 'name'

**Comment by Jinsung-L** [comment]
I think the problems caused by the renamed variables in tensor flow 0.12. [Check the release note](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md)
I changed
`            all_vars = tf.get_collection(tf.GraphKeys.VARIABLES)
`
to
`            all_vars = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
`
in `tflearn.helpers.trainer.py` then `model.fit()` and `model.save()` worked fine with no errors.
I got some warnings and errors when I loaded model though.
They all seem to related with the recently updated variable names. E.g. I got an error of these

```
WARNING:tensorflow:From /Users/jinsung/env/tensorflow012/lib/python3.5/site-packages/tflearn/helpers/trainer.py:429 in restore.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.

```
```
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'

```

**Comment by Jinsung-L** [comment]
I just found out the reason model saves the checkpoint file separately. `tf.training.Saver` class updated and now there's new version of checkpoint format which is `V2`.
I updated tflearn to explicitly use `saver_pb2.SaverDef.V1 ` then it saves checkpoint file as it did before.
You can see my change at [here](https://github.com/Jinsung-L/tflearn/commit/2ada1c0c3b95f04b2491d5ddd5d550b2545573e1)

**Comment by JiawenQi98** [comment]
Same error here. Hope an update of this script.

**Comment by gonzalolc** [comment]
It worked for me the @Jinsung-L Solution.
Done that in the usr/local/lib/python2.7/dist-packages/tflearn...

Thanks!

**Comment by aymericdamien** [comment]
Thanks for reporting issues! I am fixing that, hopefully it will be ready soon!

**Comment by Iflier** [comment]
Same here.Now, I use Tensorflow 0.12RC0 and the latest TFLearn.In the last few days, the same problem :File "D:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save
,and it bothered me for a few days.Sincerely hope to solve it as soon as possible.

**Comment by dacoconuttman** [comment]
Can confirm, still an issue in 0.12.0-rc0 in Ubuntu 16.04.1 LTS. I'm not even trying to save my graph. The error occurs when I call tflearn.DNN.

**Comment by kero13** [comment]
make tensorflow back to 0.11

**Comment by jyoungrok** [comment]
The same error occurred when I tried implementing recurrent neural network.
So I have also downgraded my tensorflow to v0.11 
I hope to get a patch for tensorflow v0.12 as soon as possible

**Comment by willduan** [comment]
@Jinsung-L I meet the same error that 
```
raise ValueError("No variables to save")
```
so How we can save model and reload it? thanks

**Comment by Jinsung-L** [comment]
@willduan You can use [this fork](https://github.com/Jinsung-L/tflearn) temporarily. Although, it's far behind from the latest version at this point.

**Comment by ssriramana93** [comment]
Hello. Is this issue resolved? I am using tensorflow 1.2.1?  I get the same error with LSTM
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing layer_tensor/BiRNN.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'list' object has no attribute 'name'

**Comment by aliray** [comment]
I have the same error @ssriramana93  Type is unsupported, or the types of the items don't match field type in CollectionDef.
'list' object has no attribute 'name'

**Comment by wronsky317** [comment]
still have the problem..

**Comment by GoingMyWay** [comment]
Similar warnings

```
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
```

TensorFlow 1.8 and tflearn 0.3.2

**Comment by Hoeze** [comment]
Tensorflow 1.9.0:

```
Error encountered when serializing while_context.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
```

**Comment by iSaran** [comment]
I get the same issue with TensorFlow 1.8 and tflearn 0.3.2 having created a graph with tflearn and using:

```python
writer = tf.summary.FileWriter("/log/path", session.graph)
```
In particular you can reproduce it using the following script and the above versions of the libraries:

```python
import tensorflow as tf
import tflearn

net = tflearn.input_data(shape=[None, 784])
net = tflearn.fully_connected(net, 64)
net = tflearn.dropout(net, 0.5)
net = tflearn.fully_connected(net, 10, activation='softmax')
net = tflearn.regression(net, optimizer='adam', loss='categorical_crossentropy')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter("/tmp/log", sess.graph)
```

The resulting warning and error:
```
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
```

**Comment by lixiang-ucas** [comment]
@iSaran have you solved this problem yet?
