### ISSUE TITLE
extract feature

### ISSUE THREAD

**Issue by ysfalo** [tflearn/tflearn#64]
How to extract extract features in a particular layer with a pre-trained model via tflearn ?

**Comment by aymericdamien** [comment]
Yes, it is fairly easy, taking the example https://github.com/tflearn/tflearn/blob/master/examples/images/dnn.py, you can add at the end of the file:
```
# Save the model
model.save('my_model')

# Redefine a model with desired layer as output
model = tflearn.DNN(dense2)
# Load weights from saved model
model.load('my_model')
# Get features for X[0]
model.predict([X[0]])
```

**Comment by mhasnat** [comment]
Hi,

My Network definition performs data pre-processing and augmentation using the following code before network definition:
===== CODE Pre-processing =====
# Real-time data preprocessing
img_prep = ImagePreprocessing()
img_prep.add_featurewise_zero_center()
img_prep.add_featurewise_stdnorm()

# Real-time data augmentation
img_aug = ImageAugmentation()
img_aug.add_random_flip_leftright()
==============

I would like to know that: "**is it necessary to do the above pre-processing before extracting features for new images**?". If yes, then please let me know how.

Thanks a lot in advance.

**Comment by aymericdamien** [comment]
If you trained your images using pre-processing, then pictures should always be pre-processed before you are going to predict (and extract features), otherwise results might changed a lot and not be consistent. But this pre-processing is done automatically by TFLearn (When training, testing and predicting), so you do not have to worry about it. Note that only data preprocessing is applied when predicting, not augmentation.

Also, I realized there was a bug when using model.predict(); it was not performing the pre-processing. I just fixed it, please re-install TFLearn and it should work fine.

**Comment by mhasnat** [comment]
Thank you for your answer. Indeed, I was applying the pre-processing before predicting and not getting the expected results. Therefore, I was wondering whether the TFLearn pre-processing has an additional impact on the test data.

Thanks for fixing the bug. I will re-install TFLearn and test it again.

**Comment by aymericdamien** [comment]
Arf... yes, I added ZCA Whitening (That added the Principal Component variable to the graph). You can either retrain your model if possible, or just add a quick fix: 
In the file: https://github.com/tflearn/tflearn/blob/master/tflearn/data_preprocessing.py#L30, Replace the PersistentParameter by 'None'. This should works well as long as your are not using ZCA Whitening.

**Comment by mhasnat** [comment]
Thanks a lot. Unfortunately adding those lines did not solve the problem. Therefore, I prefer to re-train from the beginning.

**Comment by mhasnat** [comment]
After re-training I tried to extract the features following the same way as before. However, I get the following error message now when I execute "ft = model.predict([X[0]])":

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 199, in predict
    return self.predictor.predict(feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/evaluator.py", line 63, in predict
    feed_dict[k] = dprep_dict[k].apply(feed_dict[k])
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_preprocessing.py", line 37, in apply
    batch = m(batch)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_preprocessing.py", line 187, in _featurewise_zero_center
    batch[i] -= self.global_mean.value
TypeError: ufunc 'subtract' output (typecode 'O') could not be coerced to provided output parameter (typecode 'f') according to the casting rule ''same_kind''

**Comment by aymericdamien** [comment]
Thanks for reporting the issue, there was actually a bug that the global mean variable was not restored when loading a model. I updated the code so it should work now, please reinstall TFLearn.

**Comment by mhasnat** [comment]
Thanks a lot. Now it is working as expected. Moreover, it verified my earlier assumption that the additional pre-processing has impact on the performance.

**Comment by mkhodabandeh** [comment]
Hi,
After updating tflearn today I faced similar issue:

  File "/cs/vml4/smuralid/.pyenv/versions/2.7.12/lib/python2.7/site-packages/tflearn/data_preprocessing.py", line 201, in _featurewise_zero_center
    batch[i] -= self.global_mean.value
TypeError: ufunc 'subtract' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''

Please help me fix it.

**Comment by srichakradhar** [comment]
I also have the same issue.
I'm using tflearn-0.3.2
which version is this updated in?

**Comment by stanleynguyen** [comment]
I'm having the same issue as well
tflearn==0.3.2
